CREATE TABLE `students` (
	`student_id` INT PRIMARY KEY AUTO_INCREMENT,
	`full_name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`phone_no` INT(10) NOT NULL,
	`profile_info` VARCHAR(500) NOT NULL,
	`guardian_phone` INT(10) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`gender` ENUM("Male","Female") NOT NULL,
	`national_id` INT(15) NOT NULL,
	`booked_room` INT ,
	`profile_img` VARCHAR(255),
	`is_admin` BOOLEAN DEFAULT 0,
	`created_at` VARCHAR(255) NOT NULL,
	`messages`  INT ,
	FOREIGN KEY (booked_room) REFERENCES rooms(room_id),
	FOREIGN KEY (messages) REFERENCES messages(message_id)
)

CREATE TABLE `messages`(
	`message_id`  INT PRIMARY KEY AUTO_INCREMENT,
	`message` VARCHAR(255) NOT NULL,
	`from` VARCHAR(255) NOT NULL,
	`created_at` VARCHAR(255) NOT NULL,
)

CREATE TABLE `rooms` (
	`room_id` INT PRIMARY KEY AUTO_INCREMENT,
	`hostel_name` ENUM("A-hostel","B-hostel","C-hostel",'D-hostel','E-hostel', 'F-hostel'),
	`room_no` INT NOT NULL UNIQUE,
	`booked` BOOLEAN DEFAULT 0
)

CREATE TABLE `complains`(
	`complain_id` INT PRIMARY KEY AUTO_INCREMENT,
	`from_id` INT,
	`complain` VARCHAR(255) NOT NULL,
	`created_at` VARCHAR(255) NOT NULL,
	FOREIGN KEY (from_id) REFERENCES students(student_id)
)
CREATE TABLE `notice`(
	`notice_id` INT PRIMARY KEY AUTO_INCREMENT,
	`notice_title` VARCHAR(255) NOT NULL,
	`notice_details` VARCHAR(255) NOT NULL,
	`created_at` VARCHAR(255) NOT NULL
)
-- CREATE TABLE `notifications`(
-- 	`notice_id` INT PRIMARY KEY AUTO_INCREMENT,
-- 	`notice_title` VARCHAR(255) NOT NULL,
-- 	`notice_details` VARCHAR(255) NOT NULL,
-- 	`created_at` VARCHAR(255) NOT NULL
-- )


INSERT INTO 
	rooms(hostel_name, room_no)
VALUES
	('A-hostel',1),
	('A-hostel',2),
	('A-hostel',3),
	('A-hostel',4),
	('A-hostel',5),
	('A-hostel',6),
	('A-hostel',7),
	('A-hostel',8),
	('A-hostel',9),
	('A-hostel',10),
	('A-hostel',11),
	('A-hostel',12),
	('A-hostel',13),
	('A-hostel',14),
	('A-hostel',15),
	('B-hostel',100),
	('B-hostel',102),
	('B-hostel',103),
	('B-hostel',104),
	('B-hostel',105),
	('B-hostel',106),
	('B-hostel',107),
	('B-hostel',108),
	('B-hostel',109),
	('B-hostel',110),
	('B-hostel',111),
	('B-hostel',112),
	('B-hostel',113),
	('B-hostel',114),
	('B-hostel',115),
	('C-hostel',201),
	('C-hostel',202),
	('C-hostel',203),
	('C-hostel',204),
	('C-hostel',205),
	('C-hostel',206),
	('C-hostel',207),
	('C-hostel',208),
	('C-hostel',209),
	('C-hostel',210),
	('C-hostel',211),
	('C-hostel',212),
	('C-hostel',213),
	('C-hostel',214),
	('C-hostel',215),
	('D-hostel',301),
	('D-hostel',302),
	('D-hostel',303),
	('D-hostel',304),
	('D-hostel',305),
	('D-hostel',306),
	('D-hostel',307),
	('D-hostel',308),
	('D-hostel',309),
	('D-hostel',310),
	('D-hostel',311),
	('D-hostel',312),
	('D-hostel',313),
	('D-hostel',314),
	('D-hostel',315),
	('E-hostel',401),
	('E-hostel',402),
	('E-hostel',403),
	('E-hostel',404),
	('E-hostel',405),
	('E-hostel',406),
	('E-hostel',407),
	('E-hostel',408),
	('E-hostel',409),
	('E-hostel',410),
	('E-hostel',411),
	('E-hostel',412),
	('E-hostel',413),
	('E-hostel',414),
	('E-hostel',415),
	('F-hostel',501),
	('F-hostel',502),
	('F-hostel',503),
	('F-hostel',504),
	('F-hostel',505),
	('F-hostel',506),
	('F-hostel',507),
	('F-hostel',508),
	('F-hostel',509),
	('F-hostel',510),
	('F-hostel',511),
	('F-hostel',512),
	('F-hostel',513),
	('F-hostel',514),
	('F-hostel',515);